import CryptoKit
import XCTest
@testable import Ardaas

/// Parity gate (#35): the Swift preprocessing + tokenizer must reproduce the
/// Python reference pipeline id-for-id.
///
/// Fixtures in `tokenizer_parity.json` were generated by running
/// IndicTransToolkit 1.1.1 + the reference tokenizer over 21 English
/// sentences (see the fixture `_meta` and docs/translation/README.md).
final class BentiTokenizerTests: XCTestCase {
    private struct Fixture: Decodable {
        struct Case: Decodable {
            let input: String
            let preprocessed: String
            let token_ids: [Int64]
        }
        let cases: [Case]
    }

    private static let expectedTokenizerSHA256 =
        "913a7fe797e866de46c805d237846ff6433387e77117c377fddeb28b221808da"

    private func fixtureURL(_ name: String, _ ext: String) throws -> URL {
        try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: name, withExtension: ext),
            "\(name).\(ext) missing from test bundle"
        )
    }

    private func loadFixture() throws -> Fixture {
        let data = try Data(contentsOf: try fixtureURL("tokenizer_parity", "json"))
        return try JSONDecoder().decode(Fixture.self, from: data)
    }

    private func makeTokenizer() throws -> BentiTokenizer {
        try BentiTokenizer(tokenizerFile: try fixtureURL("tokenizer_src", "json"))
    }

    /// The bundled tokenizer file must be byte-identical to the spec's
    /// downloadable artifact — otherwise parity here proves nothing about
    /// what runs on device.
    func testBundledTokenizerFileMatchesSpecHash() throws {
        let data = try Data(contentsOf: try fixtureURL("tokenizer_src", "json"))
        let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        XCTAssertEqual(digest, Self.expectedTokenizerSHA256)
    }

    func testFixtureCoverage() throws {
        let fixture = try loadFixture()
        XCTAssertGreaterThanOrEqual(fixture.cases.count, 12)
    }

    /// Moses-subset preprocessing parity: raw English -> tagged token string.
    func testPreprocessingParity() throws {
        let fixture = try loadFixture()
        for testCase in fixture.cases {
            XCTAssertEqual(
                BentiPreprocessor.preprocess(testCase.input).tagged,
                testCase.preprocessed,
                "preprocess mismatch for input: \(testCase.input)"
            )
        }
    }

    /// End-to-end encode parity: raw English -> encoder-ready ids.
    func testTokenIdParity() throws {
        let fixture = try loadFixture()
        let tokenizer = try makeTokenizer()
        for testCase in fixture.cases {
            let tagged = BentiPreprocessor.preprocess(testCase.input).tagged
            XCTAssertEqual(
                tokenizer.encode(tagged: tagged),
                testCase.token_ids,
                "token-id mismatch for input: \(testCase.input)"
            )
        }
    }

    /// Tokenizer parity in isolation (fixture `preprocessed` -> ids), so a
    /// preprocessing bug can't mask a tokenizer bug or vice versa.
    func testTokenIdParityFromPreprocessedText() throws {
        let fixture = try loadFixture()
        let tokenizer = try makeTokenizer()
        for testCase in fixture.cases {
            XCTAssertEqual(
                tokenizer.encode(tagged: testCase.preprocessed),
                testCase.token_ids,
                "token-id mismatch for preprocessed: \(testCase.preprocessed)"
            )
        }
    }

    /// The extended-vocab remap (spec section 3.6): "Gmina" BPE-resolves to
    /// fast-tokenizer id 32519 >= src_dict_size and must come out as <unk>=3.
    func testExtendedVocabRemap() throws {
        let tokenizer = try makeTokenizer()
        let ids = tokenizer.encode(tagged: "eng_Latn pan_Guru Gmina")
        XCTAssertEqual(ids, [4, 46, 3, 2])
    }

    func testLanguageTagsAndEOS() throws {
        let tokenizer = try makeTokenizer()
        let ids = tokenizer.encode(tagged: "eng_Latn pan_Guru Please")
        XCTAssertEqual(ids.first, 4)   // eng_Latn
        XCTAssertEqual(ids[1], 46)     // pan_Guru
        XCTAssertEqual(ids.last, 2)    // </s>
        XCTAssertTrue(ids.allSatisfy { $0 < 32322 })
    }

    /// One benti is one model call — there is no sentence splitting — so past
    /// the encoder's 256 positions the only honest answer is a refusal, not a
    /// silent truncation into a mistranslation.
    func testOverlongInputIsRefusedRatherThanTruncated() throws {
        XCTAssertNoThrow(
            try BentiTokenizer.validateSourceLength(
                [Int64](repeating: 5, count: BentiTokenizer.maxSourceTokens)))

        let tooMany = [Int64](repeating: 5, count: BentiTokenizer.maxSourceTokens + 1)
        XCTAssertThrowsError(try BentiTokenizer.validateSourceLength(tooMany)) { error in
            XCTAssertEqual(
                error as? TranslationError,
                .inputTooLong(
                    tokens: tooMany.count, limit: BentiTokenizer.maxSourceTokens))
        }
    }

    /// A long benti really does exceed the cap, so the guard is reachable
    /// rather than theoretical.
    func testALongBentiExceedsTheSourceLimit() throws {
        let tokenizer = try makeTokenizer()
        let sentence = String(
            repeating: "Please bless my family with health and happiness and peace. ",
            count: 40)
        let ids = tokenizer.encode(tagged: BentiPreprocessor.preprocess(sentence).tagged)
        XCTAssertGreaterThan(ids.count, BentiTokenizer.maxSourceTokens)
        XCTAssertThrowsError(try BentiTokenizer.validateSourceLength(ids))
    }
}
