import Foundation

// Spike (#35): English-side preprocessing for IndicTrans2, ported from the
// exact reference stack pinned in the pipeline spec:
//   - IndicTransToolkit 1.1.1 `IndicProcessor` (eng_Latn inference path)
//   - sacremoses 0.1.1 `MosesPunctNormalizer` (lang "en", defaults) and
//     `MosesTokenizer(lang: "en").tokenize(escape: false)`
// Correctness is gated by ArdaasTests/Fixtures/tokenizer_parity.json, which
// was generated by running the real Python pipeline over 21 sentences.
//
// Known, deliberate approximations (all invisible to English benti input,
// locked by the parity fixtures):
//   - Perl `IsAlnum`/`IsAlpha` character classes (perluniprops) are
//     approximated with ICU `\p{L}\p{M}\p{N}` / `\p{L}\p{M}`.
//   - Indic-script digit normalization (spec section 2.2) is skipped — the
//     input is English.
//   - Placeholder aliases cover the plain `<IDn>`/`[IDn]` spellings only;
//     the exotic Indic-script alias table is skipped (spec section 2.3, v1
//     recommendation).

/// A single ordered regex substitution, mirroring one `re.sub` in the
/// Python reference.
private struct RegexRule {
    let regex: NSRegularExpression
    let template: String

    init(_ pattern: String, _ template: String) {
        // Patterns are compile-time constants; an invalid one is a
        // programmer error and should crash loudly (first hit in unit tests).
        // swiftlint:disable:next force_try
        self.regex = try! NSRegularExpression(pattern: pattern)
        self.template = template
    }

    func apply(to text: String) -> String {
        regex.stringByReplacingMatches(
            in: text,
            range: NSRange(text.startIndex..., in: text),
            withTemplate: template
        )
    }
}

private extension Array where Element == RegexRule {
    func apply(to text: String) -> String {
        reduce(text) { $1.apply(to: $0) }
    }
}

private extension String {
    var strippedWhitespace: String {
        trimmingCharacters(in: .whitespacesAndNewlines)
    }
}

enum BentiPreprocessor {
    struct Output {
        /// `"eng_Latn pan_Guru <moses tokens joined by single spaces>"`
        let tagged: String
        /// Placeholder alias -> original matched text, in insertion order.
        /// Empty for typical benti input.
        let placeholders: [(alias: String, original: String)]
    }

    /// Full English preprocessing per spec section 2: punctuation
    /// normalization -> placeholder wrapping -> Moses normalize + tokenize ->
    /// language-tag prepend.
    static func preprocess(_ sentence: String) -> Output {
        var text = puncNorm(sentence)
        // Spec section 2.2 (Indic digit normalization) intentionally skipped.
        let wrapped = wrapWithPlaceholders(text)
        text = wrapped.text.strippedWhitespace
        text = mosesPunctNormalize(text)
        let tokens = mosesTokenize(text)
        return Output(
            tagged: "eng_Latn pan_Guru " + tokens.joined(separator: " "),
            placeholders: wrapped.placeholders
        )
    }

    // MARK: - IndicProcessor._punc_norm (spec section 2.1)

    private static let puncReplacements: [RegexRule] = [
        RegexRule("\\r", ""),
        RegexRule("\\(\\s*", "("),
        RegexRule("\\s*\\)", ")"),
        RegexRule("\\s:\\s?", ":"),
        RegexRule("\\s;\\s?", ";"),
        RegexRule("[`´‘‚’]", "'"),
        RegexRule("[„“”«»]", "\""),
        RegexRule("[–—]", "-"),
        RegexRule("\\.\\.\\.", "..."),
        RegexRule("\u{00A0}%", "%"),
        RegexRule("nº\u{00A0}", "nº "),
        RegexRule("\u{00A0}ºC", " ºC"),
        // Python: lambda m: m.group(0).strip() — drops the NBSP, keeps the mark.
        RegexRule("\u{00A0}([?!;])", "$1"),
        RegexRule(",\u{00A0}", ", "),
        // "Additional patterns" applied after the list, in this order:
        RegexRule("[ ]{2,}", " "),
        RegexRule("\\) ([\\.!:?;,])", ")$1"),
        RegexRule("(\\d) %", "$1%"),
        RegexRule("\"([,\\.]+)", "$1\""),
        RegexRule("(\\d)\u{00A0}(\\d)", "$1.$2"),
    ]

    static func puncNorm(_ text: String) -> String {
        puncReplacements.apply(to: text).strippedWhitespace
    }

    // MARK: - IndicProcessor._wrap_with_placeholders (spec section 2.3)

    private enum PlaceholderKind { case email, url, numeral, other }

    private static let placeholderPatterns: [(NSRegularExpression, PlaceholderKind)] = {
        func compile(_ pattern: String) -> NSRegularExpression {
            // swiftlint:disable:next force_try
            try! NSRegularExpression(pattern: pattern)
        }
        return [
            (compile("[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}"), .email),
            (compile("\\b(?<![\\w/.])(?:(?:https?|ftp)://)?(?:(?:[\\w-]+\\.)+(?!\\.))(?:[\\w/\\-?#&=%.]+)+(?!\\.\\w+)\\b"), .url),
            (compile("(~?\\d+\\.?\\d*\\s?%?\\s?-?\\s?~?\\d+\\.?\\d*\\s?%|~?\\d+%|\\d+[-/.,:']\\d+[-/.,:'+]\\d+(?:\\.\\d+)?|\\d+[-/.:'+]\\d+(?:\\.\\d+)?)"), .numeral),
            (compile("[A-Za-z0-9]*[#|@]\\w+"), .other),
        ]
    }()

    private static let whitespaceRun = RegexRule("\\s+", " ")

    static func wrapWithPlaceholders(
        _ input: String
    ) -> (text: String, placeholders: [(alias: String, original: String)]) {
        var text = input
        var placeholders: [(alias: String, original: String)] = []
        var serial = 1

        for (pattern, kind) in placeholderPatterns {
            // Unique matches. The Python reference iterates a set() (order
            // unspecified); here it's first-occurrence order, deterministic.
            var seen = Set<String>()
            var matches: [String] = []
            let range = NSRange(text.startIndex..., in: text)
            pattern.enumerateMatches(in: text, range: range) { match, _, _ in
                guard let match, let r = Range(match.range, in: text) else { return }
                let s = String(text[r])
                if seen.insert(s).inserted { matches.append(s) }
            }

            for match in matches {
                switch kind {
                case .url:
                    if match.replacingOccurrences(of: ".", with: "").count < 4 { continue }
                case .numeral:
                    if match.filter({ !" .:".contains($0) }).count < 4 { continue }
                case .email, .other:
                    break
                }

                // Plain alias spellings from the reference (Indic-script
                // aliases skipped per spec v1 recommendation).
                for alias in [
                    "<ID\(serial)>", "< ID\(serial) >", "[ID\(serial)]", "[ ID\(serial) ]",
                    "[ID \(serial)]", "<ID\(serial)]", "< ID\(serial)]", "<ID\(serial) ]",
                    "<id\(serial)>", "< id\(serial) >", "[id\(serial)]", "[ id\(serial) ]",
                    "[id \(serial)]", "<id\(serial)]", "< id\(serial)]", "<id\(serial) ]",
                ] {
                    placeholders.append((alias: alias, original: match))
                }

                text = text.replacingOccurrences(of: match, with: "<ID\(serial)>")
                serial += 1
            }
        }

        // Always runs in the reference (also collapses NBSP -> space).
        text = whitespaceRun.apply(to: text)
            .replacingOccurrences(of: ">/", with: ">")
            .replacingOccurrences(of: "]/", with: "]")
        return (text, placeholders)
    }

    // MARK: - sacremoses MosesPunctNormalizer (lang "en", penn: true,
    // norm_quote_commas: true, norm_numbers: true)

    private static let mosesNormalizerRules: [RegexRule] = [
        // EXTRA_WHITESPACE
        RegexRule("\\r", ""),
        RegexRule("\\(", " ("),
        RegexRule("\\)", ") "),
        RegexRule(" +", " "),
        RegexRule("\\) ([.!:?;,])", ")$1"),
        RegexRule("\\( ", "("),
        RegexRule(" \\)", ")"),
        RegexRule("(\\d) %", "$1%"),
        RegexRule(" :", ":"),
        RegexRule(" ;", ";"),
        // NORMALIZE_UNICODE_IF_NOT_PENN (penn=True default)
        RegexRule("`", "'"),
        RegexRule("''", " \" "),
        // NORMALIZE_UNICODE
        RegexRule("„", "\""),
        RegexRule("“", "\""),
        RegexRule("”", "\""),
        RegexRule("–", "-"),
        RegexRule("—", " - "),
        RegexRule(" +", " "),
        RegexRule("´", "'"),
        RegexRule("([a-zA-Z])‘([a-zA-Z])", "$1'$2"),
        RegexRule("([a-zA-Z])’([a-zA-Z])", "$1'$2"),
        RegexRule("‘", "'"),
        RegexRule("‚", "'"),
        RegexRule("’", "'"),
        RegexRule("''", "\""),
        RegexRule("´´", "\""),
        RegexRule("…", "..."),
        // FRENCH_QUOTES
        RegexRule("\u{00A0}«\u{00A0}", "\""),
        RegexRule("«\u{00A0}", "\""),
        RegexRule("«", "\""),
        RegexRule("\u{00A0}»\u{00A0}", "\""),
        RegexRule("\u{00A0}»", "\""),
        RegexRule("»", "\""),
        // HANDLE_PSEUDO_SPACES
        RegexRule("\u{00A0}%", "%"),
        RegexRule("nº\u{00A0}", "nº "),
        RegexRule("\u{00A0}:", ":"),
        RegexRule("\u{00A0}ºC", " ºC"),
        RegexRule("\u{00A0}cm", " cm"),
        RegexRule("\u{00A0}\\?", "?"),
        RegexRule("\u{00A0}\\!", "!"),
        RegexRule("\u{00A0};", ";"),
        RegexRule(",\u{00A0}", ", "),
        RegexRule(" +", " "),
        // EN_QUOTATION_FOLLOWED_BY_COMMA (lang == "en")
        RegexRule("\"([,.]+)", "$1\""),
        // OTHER (norm_numbers, non-de/es/cz/cs/fr)
        RegexRule("(\\d)\u{00A0}(\\d)", "$1.$2"),
    ]

    static func mosesPunctNormalize(_ text: String) -> String {
        mosesNormalizerRules.apply(to: text).strippedWhitespace
    }

    // MARK: - sacremoses MosesTokenizer("en").tokenize(escape: false)

    // Perl character-class approximations (see file header).
    private static let alnum = "\\p{L}\\p{M}\\p{N}"
    private static let alpha = "\\p{L}\\p{M}"
    private static let isN = "\\p{N}"

    private static let dedupSpace = RegexRule("\\s+", " ")
    private static let asciiJunk = RegexRule("[\\x00-\\x1F]", "")
    private static let padNotAlnum = RegexRule("([^\(alnum)\\s.'`,\\-])", " $1 ")

    private static let commaSeparate: [RegexRule] = [
        RegexRule("([^\(isN)]),", "$1 , "),
        RegexRule(",([^\(isN)])", " , $1"),
        RegexRule("([\(isN)]),$", "$1 , "),
    ]

    private static let englishApostrophe: [RegexRule] = [
        RegexRule("([^\(alpha)])'([^\(alpha)])", "$1 ' $2"),
        RegexRule("([^\(alpha)\(isN)])'([\(alpha)])", "$1 ' $2"),
        RegexRule("([\(alpha)])'([^\(alpha)])", "$1 ' $2"),
        RegexRule("([\(alpha)])'([\(alpha)])", "$1 '$2"),
        RegexRule("([\(isN)])'([s])", "$1 '$2"),
    ]

    private static let multidotStart = RegexRule("\\.(\\.+)", " DOTMULTI$1")
    private static let dotmultiDotChar = RegexRule("DOTMULTI\\.([^\\.])", "DOTDOTMULTI $1")
    private static let dotmultiDot = RegexRule("DOTMULTI\\.", "DOTDOTMULTI")
    private static let trailingDotApostrophe = RegexRule("\\.' ?$", " . ' ")

    static func mosesTokenize(_ input: String) -> [String] {
        var text = dedupSpace.apply(to: input)
        text = asciiJunk.apply(to: text)
        text = text.strippedWhitespace
        text = padNotAlnum.apply(to: text)
        text = replaceMultidots(text)
        text = commaSeparate.apply(to: text)
        text = englishApostrophe.apply(to: text)
        text = handleNonbreakingPrefixes(text)
        text = dedupSpace.apply(to: text).strippedWhitespace
        text = trailingDotApostrophe.apply(to: text)
        text = restoreMultidots(text)
        return text.split(separator: " ").map(String.init)
    }

    private static func replaceMultidots(_ input: String) -> String {
        var text = multidotStart.apply(to: input)
        while text.range(of: "DOTMULTI\\.", options: .regularExpression) != nil {
            text = dotmultiDotChar.apply(to: text)
            text = dotmultiDot.apply(to: text)
        }
        return text
    }

    private static func restoreMultidots(_ input: String) -> String {
        var text = input
        while text.contains("DOTDOTMULTI") {
            text = text.replacingOccurrences(of: "DOTDOTMULTI", with: "DOTMULTI.")
        }
        return text.replacingOccurrences(of: "DOTMULTI", with: ".")
    }

    // MARK: - Nonbreaking prefixes (sacremoses en list)

    /// sacremoses `nonbreaking_prefix.en`, minus the `#NUMERIC_ONLY#` entries
    /// (kept separately below, matching how the reference checks membership).
    private static let nonbreakingPrefixes: Set<String> = [
        "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
        "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
        "Adj", "Adm", "Adv", "Asst", "Bart", "Bldg", "Brig", "Bros", "Capt",
        "Cmdr", "Col", "Comdr", "Con", "Corp", "Cpl", "DR", "Dr", "Drs",
        "Ens", "Gen", "Gov", "Hon", "Hr", "Hosp", "Insp", "Lt", "MM", "MR",
        "MRS", "MS", "Maj", "Messrs", "Mlle", "Mme", "Mr", "Mrs", "Ms",
        "Msgr", "Op", "Ord", "Pfc", "Ph", "Prof", "Pvt", "Rep", "Reps",
        "Res", "Rev", "Rt", "Sen", "Sens", "Sfc", "Sgt", "Sr", "St", "Supt",
        "Surg", "v", "vs", "i.e", "rev", "e.g", "Rs", "Nos", "Nr",
        "Jan", "Feb", "Mar", "Apr", "Jun", "Jul", "Aug", "Sep", "Oct",
        "Nov", "Dec",
    ]

    /// Prefixes that only stay attached when followed by a number
    /// ("No #NUMERIC_ONLY#", "Art #NUMERIC_ONLY#", "pp #NUMERIC_ONLY#").
    private static let numericOnlyPrefixes: Set<String> = ["No", "Art", "pp"]

    private static func isAnyAlpha(_ text: String) -> Bool {
        text.unicodeScalars.contains { $0.properties.isAlphabetic }
    }

    private static func isLower(_ scalar: Unicode.Scalar) -> Bool {
        scalar.properties.isLowercase
    }

    static func handleNonbreakingPrefixes(_ text: String) -> String {
        var tokens = text.split(separator: " ").map(String.init)
        for i in tokens.indices {
            let token = tokens[i]
            // Python: re.search(r"^(\S+)\.$", token)
            guard token.hasSuffix("."), token.count >= 2 else { continue }
            let prefix = String(token.dropLast())

            let keepAttached =
                (prefix.contains(".") && isAnyAlpha(prefix))
                || nonbreakingPrefixes.contains(prefix)
                || (i != tokens.count - 1
                    && !tokens[i + 1].isEmpty
                    && isLower(tokens[i + 1].unicodeScalars.first!))
            if keepAttached { continue }

            let numericKeep =
                numericOnlyPrefixes.contains(prefix)
                && i + 1 < tokens.count
                && tokens[i + 1].unicodeScalars.first.map { (48...57).contains($0.value) } == true
            if numericKeep { continue }

            tokens[i] = prefix + " ."
        }
        return tokens.joined(separator: " ")
    }
}
